ingress:
  # Photon Ingress Configuration
  - ingressName: priobike-photon-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /photon/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-photon-service
    servicePort: 2322

  # Auth Ingress Configuration
  - ingressName: priobike-auth-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /auth/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-auth-service
    servicePort: 80

  # Graphhopper DRN Ingress Configuration
  - ingressName: priobike-graphhopper-drn-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /drn-graphhopper/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-graphhopper-drn-service
    servicePort: 8989

  # Overpass DRN Ingress Configuration
  - ingressName: priobike-overpass-drn-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /drn-overpass/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-overpass-drn-service
    servicePort: 80

  # POI Ingress Configuration
  - ingressName: priobike-poi-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /poi-service-backend/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-poi-service
    servicePort: 8000

  # SG Selector Ingress Configuration
  - ingressName: priobike-sg-selector-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /sg-selector-backend/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-sg-selector-service
    servicePort: 8000

  # SG Selector NGINX Ingress Configuration
  - ingressName: priobike-sg-selector-nginx-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /sg-selector-nginx/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-sg-selector-nginx-service
    servicePort: 80

  # Privacy Policy Ingress Configuration
  - ingressName: priobike-privacy-policy-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /privacy-policy
    pathType: Prefix
    serviceName: priobike-privacy-policy-service
    servicePort: 80

  # Shlink Ingress Configurations (order matters to make sure that the most specific path is matched first)
  - ingressName: priobike-shlink-cache-ingress-get-via-app
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /rest/v3/short-urls/$1
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($request_method != GET) {
          return 405;
        }
    path: /link/rest/v3/short-urls/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-shlink-cache-service
    servicePort: 80
  - ingressName: priobike-shlink-cache-ingress-post
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /rest/v3/short-urls
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($request_method != POST) {
          return 405;
        }
    path: /link/rest/v3/short-urls
    pathType: Exact
    serviceName: priobike-shlink-cache-service
    servicePort: 80
  - ingressName: priobike-shlink-cache-ingress-get-via-browser
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($request_method != GET) {
          return 405;
        }
    path: /link/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-shlink-cache-service
    servicePort: 80

priobike-mqtt:
  mqttAuthenticatorServiceName: priobike-mqtt-authenticator-service
  mqttAuthenticatorContainerPort: 8000
  nodePort: 30000

priobike-mqtt-authenticator:
  passwords: 123456789,sdirugbhriuhg

priobike-shlink:
  initialApiKey: 0841ab0f-bf12-4859-b731-8316de1f9e5b
  dbName: shlink
  dbUser: shlink
  dbPassword: shlink
  defaultHost: localhost/link
  dbDriver: postgres

priobike-shlink-cache:
  originServiceName: priobike-shlink-guard-service
  originServicePort: 8000
  configMapName: priobike-shlink-cache-config
  deploymentName: priobike-shlink-cache-deployment
  containerName: priobike-shlink-cache-container
  serviceName: priobike-shlink-cache-service
  ingressName: priobike-shlink-cache-ingress
  labels:
    app: priobike-shlink-cache-app
  path: /link(/|$)(.*)
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

priobike-shlink-postgres:
  fullnameOverride: priobike-shlink-postgres-service
  auth:
    username: shlink
    password: shlink
    database: shlink
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      enabled: true
      size: 1Gi
    persistentVolumeClaimRetentionPolicy:
      enabled: true

global:
  namespace: priobike-k8s-deployment
  priobikeImageRegistry: bikenow.vkw.tu-dresden.de/priobike

