priobike-privacy-policy-service:
  replicas: 2

priobike-mqtt:
  mqttAuthenticatorServiceName: priobike-mqtt-authenticator-service
  mqttAuthenticatorContainerPort: 8000

priobike-mqtt-authenticator:
  passwords: 123456789,sdirugbhriuhg

global:
  namespace: priobike-k8s-deployment
