basicAuthSecrets:
  - secretName: priobike-news-manager-basic-auth
    htpasswdFileContent: foo:$apr1$DktyLw42$0zMeN9fPwQwFyvLXpU3qg/ # user: foo, pw: bar
  - secretName: priobike-tracking-manager-basic-auth
    htpasswdFileContent: foo:$apr1$DktyLw42$0zMeN9fPwQwFyvLXpU3qg/ # user: foo, pw: bar

ingress:
  # FROST Mirror Ingress Configuration
  - ingressName: priobike-frost-mirror-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /priobike-frost-mirror/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-map-data-service
    servicePort: 8080

  # Map Data Ingress Configuration
  - ingressName: priobike-map-data-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /map-data/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-map-data-service
    servicePort: 80

  # Tracking Worker Ingress Configuration
  - ingressName: priobike-tracking-worker-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /tracking-service/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-tracking-worker-service
    servicePort: 8000

  # Tracking Manager Ingress Configuration
  - ingressName: priobike-tracking-manager-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /admin/$1
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: priobike-tracking-manager-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
    path: /tracking-service-manager/admin/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-tracking-manager-service
    servicePort: 8000

  # News Worker Ingress Configuration
  - ingressName: priobike-news-worker-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /news-service/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-news-worker-service
    servicePort: 8000

  # News Manager Ingress Configuration
  - ingressName: priobike-news-manager-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /admin/$1
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: priobike-news-manager-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
    path: /news-service-manager/admin/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-news-manager-service
    servicePort: 8000

  # Photon Ingress Configuration
  - ingressName: priobike-photon-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /photon/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-photon-service
    servicePort: 2322

  # Auth Ingress Configuration
  - ingressName: priobike-auth-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /auth/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-auth-service
    servicePort: 80

  # Graphhopper DRN Ingress Configuration
  - ingressName: priobike-graphhopper-drn-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /drn-graphhopper/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-graphhopper-drn-service
    servicePort: 8989

  # Overpass DRN Ingress Configuration
  - ingressName: priobike-overpass-drn-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /drn-overpass/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-overpass-drn-service
    servicePort: 80

  # POI Ingress Configuration
  - ingressName: priobike-poi-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /poi-service-backend/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-poi-service
    servicePort: 8000

  # SG Selector Ingress Configuration
  - ingressName: priobike-sg-selector-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /sg-selector-backend/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-sg-selector-service
    servicePort: 8000

  # SG Selector NGINX Ingress Configuration
  - ingressName: priobike-sg-selector-nginx-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /sg-selector-nginx/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-sg-selector-nginx-service
    servicePort: 80

  # Privacy Policy Ingress Configuration
  - ingressName: priobike-privacy-policy-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /privacy-policy
    pathType: Prefix
    serviceName: priobike-privacy-policy-service
    servicePort: 80

  # Shlink Ingress Configurations (order matters to make sure that the most specific path is matched first)
  - ingressName: priobike-shlink-cache-ingress-get-via-app
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /rest/v3/short-urls/$1
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($request_method != GET) {
          return 405;
        }
    path: /link/rest/v3/short-urls/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-shlink-cache-service
    servicePort: 80
  - ingressName: priobike-shlink-cache-ingress-post
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /rest/v3/short-urls
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($request_method != POST) {
          return 405;
        }
    path: /link/rest/v3/short-urls
    pathType: Exact
    serviceName: priobike-shlink-cache-service
    servicePort: 80
  - ingressName: priobike-shlink-cache-ingress-get-via-browser
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($request_method != GET) {
          return 405;
        }
    path: /link/(.*)
    pathType: ImplementationSpecific
    serviceName: priobike-shlink-cache-service
    servicePort: 80

priobike-frost-mirror:
  persistenceDbUsername: postgres
  persistenceDbPassword: frost-password
  serviceRootUrl: http://localhost/priobike-frost-mirror/FROST-Server

priobike-news:
  syncKey: "123456789"
  djangoKey: abcdefghijklmnopqrstuvwxyz
  csrfTrustedOrigin: http://localhost
  manager:
    djangoSuperuserPassword: blablabla
    fcmPushNotificationEnvironment: development

priobike-tracking:
  syncKey: seghseherhs
  djangoKey: werhwerhwerhwerhwerhwjzweiiow
  csrfTrustedOrigin: http://localhost
  manager:
    djangoSuperuserPassword: bliblablub
    apiKey: totallySecureApiKey

priobike-mqtt:
  mqttAuthenticatorServiceName: priobike-mqtt-authenticator-service
  mqttAuthenticatorContainerPort: 8000
  nodePort: 30000

priobike-mqtt-authenticator:
  passwords: 123456789,sdirugbhriuhg

priobike-shlink:
  initialApiKey: 0841ab0f-bf12-4859-b731-8316de1f9e5b
  dbName: shlink
  dbUser: shlink
  dbPassword: shlink
  defaultHost: localhost/link
  dbDriver: postgres

priobike-shlink-cache:
  originServiceName: priobike-shlink-guard-service
  originServicePort: 8000
  configMapName: priobike-shlink-cache-config
  deploymentName: priobike-shlink-cache-deployment
  containerName: priobike-shlink-cache-container
  serviceName: priobike-shlink-cache-service
  ingressName: priobike-shlink-cache-ingress
  labels:
    app: priobike-shlink-cache-app
  path: /link(/|$)(.*)
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

priobike-shlink-postgres:
  fullnameOverride: priobike-shlink-postgres-service
  auth:
    username: shlink
    password: shlink
    database: shlink
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      enabled: true
      size: 1Gi
    persistentVolumeClaimRetentionPolicy:
      enabled: true

global:
  namespace: priobike-k8s-deployment
  priobikeImageRegistry: bikenow.vkw.tu-dresden.de/priobike
