priobike-mqtt:
  mqttAuthenticatorServiceName: priobike-mqtt-authenticator-service
  mqttAuthenticatorContainerPort: 8000
  nodePort: 30000 

priobike-mqtt-authenticator:
  passwords: 123456789,sdirugbhriuhg

priobike-shlink:
  initialApiKey: 0841ab0f-bf12-4859-b731-8316de1f9e5b
  dbName: shlink
  dbUser: shlink
  dbPassword: shlink
  defaultHost: localhost/link
  dbDriver: postgres

priobike-shlink-cache:
  originServiceName: priobike-shlink-guard-service
  originServicePort: 8000
  configMapName: priobike-shlink-cache-config
  deploymentName: priobike-shlink-cache-deployment
  containerName: priobike-shlink-cache-container
  serviceName: priobike-shlink-cache-service
  ingressName: priobike-shlink-cache-ingress
  labels:
    app: priobike-shlink-cache-app
  path: /link(/|$)(.*)
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

priobike-shlink-postgres:
  fullnameOverride: priobike-shlink-postgres-service
  auth:
    username: shlink
    password: shlink
    database: shlink
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      enabled: true
      size: 1Gi
    persistentVolumeClaimRetentionPolicy:
      enabled: true

global:
  namespace: priobike-k8s-deployment
  priobikeImageRegistry: bikenow.vkw.tu-dresden.de/priobike
